spring:
  main:
    web-application-type: none
  application:
    name: file-analysis-system
  datasource:
    url: ${SPRING_DATASOURCE_URL}
    username: ${SPRING_DATASOURCE_USERNAME}
    password: ${SPRING_DATASOURCE_PASSWORD}
    driver-class-name: org.postgresql.Driver
  jpa:
    show-sql: true
    hibernate:
      ddl-auto: update
    properties:
      hibernate:
        dialect: org.hibernate.dialect.PostgreSQLDialect
        format_sql: true


grpc:
  server:
    port: ${GRPC_PORT:50051}
  client:
    file-storing-service:
      address: file-storing-service:50051
      negotiation-type: plaintext